### ISSUE TITLE
Why the weights of CMSIS-NN's CIFAR10 example are not the same as the weights generated by the code generator ?

### ISSUE THREAD

**Issue by baileo** [ARM-software/ML-examples#2]
Why are the following three weights different?

https://github.com/ARM-software/CMSIS_5/blob/develop/CMSIS/NN/Examples/ARM/arm_nn_examples/cifar10/arm_nnexamples_cifar10_weights.h

https://github.com/ARM-software/ML-examples/blob/master/cmsisnn-cifar10/code/m7/weights.h

https://github.com/ARM-software/ML-examples/blob/master/cmsisnn-cifar10/code/m4/weights.h

**Comment by navsuda** [comment]
Hi @baileo,
Please see [this](https://github.com/ARM-software/CMSIS_5/issues/373#issuecomment-392126926). In short, you are looking at weights generated from different models, hence they are different.
