### ISSUE TITLE
./mnist-caffe cannot load armnn .so libraries

### ISSUE THREAD

**Issue by andrej-dev** [ARM-software/ML-examples#26]
Hello!
I spent some time setting up the ARM NN SDK on my nVidia Jetson board and have passed and gone through all the manuals (compute library, caffe, armnn and tests). I am now trying to run an example from ML-examples - mnist. I modified the makefile and it builds fine. But, when I try to run ./mnist-caffe I keep getting error 40 - cannot load two .so libraries from ARMNN. I tried to copy these into the local folder, I created symbolic links to them in /usr/lib but nothing seems to help...

Is there a simple solution to this issue? An alternative is that I try to build armnn static libraries but for that I would need instructions...

Thanks!

**Comment by Yooong-W** [comment]
> 解决。谢谢。

Hi, I have encountered the same problem. How do you solve it?

**Comment by andrej-dev** [comment]
Set LD_LIBRARY_PATH to where your libraries are.
