### ISSUE TITLE
On what IDE should i run these examples ? ( I'm a Dummy) How do i get started ?

### ISSUE THREAD

**Issue by praisonjoshua** [ARM-software/ML-examples#6]
i reffered their how-to-guide which i couldnt understand 
I need hand holding to run mnist caffe implementation ,
1. which ide is preffered ?
2. how to setup armnn practicaly in windows ?

**Comment by mark-arm** [comment]
There is no preferred IDE, but Windows is not currently supported by these examples. I recommend Ubuntu 16.04, but some familiarity with Makefiles and the command line is required.
