### ISSUE TITLE
Wrong col_buffer size/type ?

### ISSUE THREAD

**Issue by iabdalkader** [ARM-software/ML-examples#7]
Hi, the attached network causes memory corruption when run a few times on Cortex-M7. I think the col_buffer size/type is wrong. The generated code allocates a col_buffer of 800, but gdb breaks on writes almost twice the size, doubling the col_buffer size fixes the issue for now.

[square.pkl.zip](https://github.com/ARM-software/ML-examples/files/2442933/square.pkl.zip)

**Comment by navsuda** [comment]
@iabdalkader,
Please look at the output of these [print](https://github.com/ARM-software/ML-examples/blob/master/cmsisnn-cifar10/code_gen.py#L190) statements to understand which NN layer is causing this issue and report it. Can you also share your square_train_test.prototxt and give details on which layer gdb shows the error?

**Comment by iabdalkader** [comment]
@navsuda Hi, were you able to reproduce the bug ?

**Comment by navsuda** [comment]
@iabdalkader,
Not really (need caffemodel too to reproduce it), but your debug log was sufficient to find the bug. Pushed a fix, see if it helps. 
It should generate
`Layer: ip1, required memory: 1024, im2col buffer size: 1024`

**Comment by iabdalkader** [comment]
@navsuda Thanks! I also [fixed](https://github.com/openmv/openmv/commit/4449cbe36968a2a405b9f7353041d1ad27dfd0c5) my C code the same way, and I can confirm it fixes the issue and my test networks run fine.
